PATCH http://localhost:3000/user/1
Content-Type: application/json

{"UserName" : "Jeff"}

###

GET http://localhost:3000/api/users/1/platerboxes

###

GET http://localhost:3000/api/planterboxes/1/setting